language: python

install:
    - pip install pipenv

python:
    - "3.6"
    - "3.7-dev"

matrix:
    include:
        - python: "3.7"
          dist: xenial
          sudo: true

script: make checklist

after_success:
    - codecov
