language: python

install:
    - pip install pipenv

python:
    - "3.6"
    - "3.7"
    - "3.7-dev"
    - "3.8-dev"

matrix:
    include:
        - python: "3.7"
          dist: xenial
          sudo: true
    allow_failures:
        - python: "3.7-dev"
        - python: "3.8-dev"

script: make checklist

after_success:
    - codecov
